http:

  routers:
    HomeAssistant:
      entryPoints:
        - https
      rule: 'Host(`home.example.com`)'
      middlewares:
        ##- "auth"
        - securityHeaders
      tls: {}
      service: HomeAssistant
    Pihole:
      entryPoints:
        - https
      rule: 'Host(`pihole.example.com`)'
      middlewares:
        - securityHeaders
        - pihole-redirect
      tls: {}
      service: Pihole
          ## SERVERS ##
  services:
    HomeAssistant:
      loadBalancer:
        servers:
          - url: "http://[IP]:[PORT]"
        passHostHeader: true
    Pihole:
      loadBalancer:
        servers:
          - url: "http://[IP]:80"
        passHostHeader: true
          ## MIDDLEWARES ##
  middlewares:
    https-redirect:
       redirectScheme:
         scheme: https
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    pihole-redirect:
      redirectRegex:
        regex: "^https?://pihole.example.com/$" #I think this can be replaced with addPrefix:
        replacement: "https://pihole.example.com/admin/" # prefix: "/admin"

    # Only Allow Local networks
    #local-ipwhitelist:
    # ipWhiteList:
     #  sourceRange: 
     #    - 127.0.0.1/32 # localhost
     #    - 192.168.0.0/16
     #    - 172.16.0.0./16
     #    - 10.10.0.0/16
  
    # Authelia guard
    auth:
      forwardauth:
        address: http://auth:9091/api/verify?rd=https://auth.domain.com/ # replace auth with your authelia container name
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
  
    # Authelia basic auth guard
    auth-basic:
      forwardauth:
        address: http://auth:9091/api/verify?auth=basic # replace auth with your authelia container name
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    secured:
      chain:
        middlewares:
        - securityHeaders
    sonarr-dark:
      plugin:
        themepark:
          # The name of the supported application listed on https://docs.theme-park.dev/themes.
          app: sonarr

          # The name of the supported theme listed on https://docs.theme-park.dev/theme-options/ or https://docs.theme-park.dev/community-themes/
          theme: dark

          # baseUrl is optional if you want to use a self-hosted version of theme.park
          #baseUrl: https://theme-park.domain.tld

          # This currently only supports '4k-logo' and 'darker' addons. Future addons that follow a similar syntax will work as well.
          # For refernce: https://docs.theme-park.dev/themes/addons/
          addons:
            - sonarr-4k-logo
    radarr-theme:
      plugin:
        themepark:
          # The name of the supported application listed on https://docs.theme-park.dev/themes.
          app: radarr

          # If using the 'darker' addon the theme MUST be excluded or set to 'base'
          theme: base

          # Multiple addons can be included at the same time
          addons:
            - radarr-darker
            - radarr-4k-logo
    my-sablier:
      plugin:
        sablier:
          dynamic:
            displayName: My Title
            refreshFrequency: 5s
            showDetails: "true"
            theme: hacker-terminal
          group: default
          names: guacamole
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
# Only use secure ciphers - https://ssl-config.mozilla.org/#server=traefik&version=2.6.0&config=intermediate&guideline=5.6
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
