version: '2'
services:
    beammp-server:
        image: rouhim/beammp-server
        container_name: beammp-server
        ports:
            - '30814:30814/tcp'
            - '30814:30814/udp'
        environment:
            - NAME=
            - AUTH_KEY=
            - MAP=