version: "3.8"
services:
  tectonic:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.4
      MODRINTH_PROJECTS: |
        tectonic:H8adpDEF
        fabric-api:htRy7kbI
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - /portainer/Files/AppData/Config/Tectonic-data:/data