---
networks:
  onlyoffice-network:
    external: true
volumes:
  redis-nextcloud-data:
  redis-onlyoffice-document-data:
  rabbitmq-onlyoffice-document-data:
  onlyoffice-document-data:
  onlyoffice-document-log:
  onlyoffice-document-cache-files:
  onlyoffice-document-public-files:
  onlyoffice-document-fonts:  
  
services:
  redis-onlyoffice-document:
    image: redis:7.0
    volumes:
      - redis-onlyoffice-document-data:/data
    networks:
      - onlyoffice-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  rabbitmq-onlyoffice-document:
    image: bitnami/rabbitmq:3.12
    volumes:
      - rabbitmq-onlyoffice-document-data:/bitnami/rabbitmq/mnesia
    environment:
      RABBITMQ_USERNAME: ${ONLYOFFICE_DOCUMENT_RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${ONLYOFFICE_DOCUMENT_RABBITMQ_PASSWORD}
    expose:
      - '5672'
    networks:
      - onlyoffice-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: unless-stopped

  onlyoffice-document:
    image: onlyoffice/documentserver:8.0.1
    volumes:
      - onlyoffice-document-data:/var/www/onlyoffice/Data
      - onlyoffice-document-log:/var/log/onlyoffice
      - onlyoffice-document-cache-files:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - onlyoffice-document-public-files:/var/www/onlyoffice/documentserver-example/public/files
      - onlyoffice-document-fonts:/usr/share/fonts
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${ONLYOFFICE_DOCUMENT_DB_NAME}
      DB_USER: ${ONLYOFFICE_DOCUMENT_DB_USER}
      DB_PWD: ${ONLYOFFICE_DOCUMENT_DB_PASSWORD}
      AMQP_URI: amqp://${ONLYOFFICE_DOCUMENT_RABBITMQ_USER}:${ONLYOFFICE_DOCUMENT_RABBITMQ_PASSWORD}@onlyoffice-test-rabbitmq-onlyoffice-document-1
      REDIS_SERVER_HOST: redis-onlyoffice-document
      REDIS_SERVER_PORT: 6379
      JWT_ENABLED: true
      JWT_SECRET: ${ONLYOFFICE_DOCUMENT_JWT_SECRET}
      JWT_HEADER: Authorization
      JWT_IN_BODY: 'true'
    networks:
      - onlyoffice-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice-document.rule=Host(`${ONLYOFFICE_DOCUMENT_HOSTNAME}`)"
      - "traefik.http.routers.onlyoffice-document.service=onlyoffice-document"
      - "traefik.http.routers.onlyoffice-document.entrypoints=websecure"
      - "traefik.http.services.onlyoffice-document.loadbalancer.server.port=80"
      - "traefik.http.routers.onlyoffice-document.tls=true"
    restart: unless-stopped
    depends_on:
      rabbitmq-onlyoffice-document:
        condition: service_healthy