version: '3.8'
services:
  vanilla:
    image: itzg/minecraft-server
    environment:
      TYPE: ${VANILLA_TYPE}
      ONLINE_MODE: ${OM}
      EULA: "TRUE"
      VERSION: ${VANILLA_VERSION}
      TZ: ${TZ}
      UID: ${VANILLA_UID}
      GID: ${VANILLA_GID}
      MEMORY: ${VANILLA_MEM}
      PLUGINS: |
        https://download.luckperms.net/1534/fabric/LuckPerms-Fabric-5.4.121.jar
      MODRINTH_PROJECTS: |
        fabricproxy-lite:Mxw3Cbsk
        fabric-api:htRy7kbI
        dynamic-lights:Y1UP7YoY
        fallingtree:mb15RrXi
        inventory-sorting:MO3Q3zs2
        jei:HPR5ThoH
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - Vanilla:/data
    networks:
      - mc
    restart: unless-stopped

  tectonic:
    image: itzg/minecraft-server
    environment:
      TYPE: ${TECT_TYPE}
      ONLINE_MODE: ${OM}
      EULA: "TRUE"
      VERSION: ${TECT_VERSION}
      TZ: ${TZ}
      UID: ${TECT_UID}
      GID: ${TECT_UID}
      MEMORY: ${TECT_MEM}
      VIEW_DISTANCE: ${TECT_VIEW}
      SIMULATION_DISTANCE: ${TECT_SIM}
      MODRINTH_PROJECTS: |
        fabric-api:htRy7kbI
        fabricproxy-lite:Mxw3Cbsk
        tectonic:H8adpDEF
        journeymap:YzYzLujr
        fallingtree:mb15RrXi
        dynamic-lights:Y1UP7YoY
        inventory-sorting:MO3Q3zs2
        jei:HPR5ThoH
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - Tectonic:/data
    networks:
      - mc
    restart: unless-stopped

  Creative:
    image: itzg/minecraft-server
    environment:
      UID: ${CREA_UID}
      GID: ${CREA_UID}
      TYPE: ${CREA_TYPE}
      STOP_SERVER_ANNOUNCE_DELAY: 30
      MODE: CREATIVE
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 12
      LEVEL_TYPE: "minecraft:flat"
      EULA: "TRUE"
      VERSION: ${CREA_VER}
      TZ: ${TZ}
      ONLINE_MODE: FALSE
      PVP: FALSE
      DIFFICULTY: PEACEFUL
      ALLOW_NETHER: FALSE     
      MEMORY: ${CREA_MEM}
      PLUGINS: |
        https://download.luckperms.net/1534/fabric/LuckPerms-Fabric-5.4.121.jar
      MODRINTH_PROJECTS: |
        fabricproxy-lite:Mxw3Cbsk
        tectonic:H8adpDEF
        journeymap:YzYzLujr
        fallingtree:mb15RrXi
        dynamic-lights:Y1UP7YoY
        inventory-sorting:MO3Q3zs2
        jei:HPR5ThoH
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - Creative:/data
    networks:
      - Oasis
    ports: 
      - 25566:25565
    restart: unless-stopped

  Mining:
    image: itzg/minecraft-server
    environment:
      UID: ${MINE_UID}
      GID: ${MINE_UID}
      TYPE: ${MINE_TYPE}
      STOP_SERVER_ANNOUNCE_DELAY: 90
      LEVEL_TYPE: "minecraft:amplified"
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      SIMULATION_DISTANCE: ${MINE_SIM}
      EULA: "TRUE"
      VERSION: ${MINE_MEM}
      TZ: ${TZ}
      PVP: FALSE
      ONLINE_MODE: FALSE
      DIFFICULTY: EASY
      MEMORY: ${MINE_MEM}
      PLUGINS: |
        https://download.luckperms.net/1534/fabric/LuckPerms-Fabric-5.4.121.jar
      MODRINTH_PROJECTS: |
        fabricproxy-lite:Mxw3Cbsk
        fabric-api:htRy7kbI
        fallingtree:mb15RrXi
        dynamic-lights:Y1UP7YoY
        journeymap:YzYzLujr
        inventory-sorting:MO3Q3zs2
        jei:HPR5ThoH
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - Mining:/data
    networks:
      - Oasis
    ports: 
      - 25567:25565
    restart: unless-stopped
  
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    depends_on:
      - vanilla
      - tectonic
    environment:
      TZ: "America/New_York"
      MAPPING: |
        vanilla.example.com=oasis-vanilla-1:25565
        tectonic.example.com=oasis-tectonic-1:25565
    networks:
      - mc
    restart: unless-stopped

  proxy:
    image: itzg/bungeecord
    environment:
      TYPE: VELOCITY
      MINECRAFT_VERSION: 1.20.4
      MEMORY: 2G
      DEBUG: "false"
      ENABLE_RCON: "true"
      PLUGINS: |
        https://hangarcdn.papermc.io/plugins/ReModded/ReWhitelist/versions/1.0.0/VELOCITY/ReWhitelist-1.0.0.jar
        https://download.luckperms.net/1534/velocity/LuckPerms-Velocity-5.4.121.jar
      MODRINTH_PROJECTS: |
        minimotd:z8DFFJMR
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    networks:
      - mc
    ports:
      - "25565:25577"
    volumes:
      - proxy:/server
    
networks:
  mc:
    name: mc
    driver: bridge

volumes:
  proxy:
    external: true
  Tectonic:
    external: true
  Vanilla:
    external: true
