version: '3.8'
services:
  Creative:
    image: itzg/minecraft-server
    environment:
      UID: ${CREA_UID}
      GID: ${CREA_UID}
      TYPE: ${CREA_TYPE}
      STOP_SERVER_ANNOUNCE_DELAY: 30
      MODE: CREATIVE
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 12
      LEVEL_TYPE: "minecraft:flat"
      EULA: "TRUE"
      VERSION: ${CREA_VER}
      TZ: ${TZ}
      ONLINE_MODE: FALSE
      PVP: FALSE
      DIFFICULTY: PEACEFUL
      ALLOW_NETHER: FALSE     
      MEMORY: ${CREA_MEM}
      PLUGINS: |
        https://download.luckperms.net/1534/fabric/LuckPerms-Fabric-5.4.121.jar
        https://github.com/EssentialsX/Essentials/releases/tag/2.20.1
        https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar
        https://cdn.modrinth.com/data/SVKv1SZo/versions/G36ffHrs/iCommon-Fabric-bundle.jar
      MODRINTH_PROJECTS: |
        fabricproxy-lite:Mxw3Cbsk
        tectonic:H8adpDEF
        journeymap:YzYzLujr
        fallingtree:mb15RrXi
        dynamic-lights:Y1UP7YoY
        inventory-sorting:MO3Q3zs2
        jei:HPR5ThoH
        no-chat-reports:tfv6A4l5
        cardboard:yNNUJI0X
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - Creative:/data
    networks:
      - Oasis
    ports: 
      - 25566:25565
    restart: unless-stopped

  Mining:
    image: itzg/minecraft-server
    environment:
      UID: ${MINE_UID}
      GID: ${MINE_UID}
      TYPE: ${MINE_TYPE}
      STOP_SERVER_ANNOUNCE_DELAY: 90
      LEVEL_TYPE: "minecraft:amplified"
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      SIMULATION_DISTANCE: ${MINE_SIM}
      EULA: "TRUE"
      VERSION: ${MINE_MEM}
      TZ: ${TZ}
      PVP: FALSE
      ONLINE_MODE: FALSE
      DIFFICULTY: EASY
      MEMORY: ${MINE_MEM}
      PLUGINS: |
        https://download.luckperms.net/1534/bukkit/loader/LuckPerms-Bukkit-5.4.121.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsXChat-2.20.1.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsXSpawn-2.20.1.jar
        https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar
        https://dev.bukkit.org/projects/worldguard/files/4675318/download
        https://dev.bukkit.org/projects/grief-prevention/files/5115771/download
        https://get.discordsrv.com/
        https://dev.bukkit.org/projects/thizzyz-tree-feller/files/latest
        https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/15.0.9/SkinsRestorer.jar
        https://hangarcdn.papermc.io/plugins/HelpChat/PlaceholderAPI/versions/2.11.5/PAPER/PlaceholderAPI-2.11.5.jar
        https://hangarcdn.papermc.io/plugins/Archy/AuraSkills/versions/2.0.7/PAPER/AuraSkills-2.0.7.jar
        https://hangarcdn.papermc.io/plugins/pop4959/Chunky/versions/1.3.136/PAPER/Chunky-1.3.136.jar
      SPIGET_RESOURCES: |
        78766
        40313
        102931
      MODRINTH_PROJECTS: |
        veinminer:11brGK6s
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - Mining:/data
    networks:
      - Oasis
    ports: 
      - 25567:25565
    restart: unless-stopped
  
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    depends_on:
      - proxy
    environment:
      TZ: "America/New_York"
      MAPPING: |
        mc.l3lee.com=oasis-proxy-1:25577
    ports:
      - "25570:25565"
    networks:
      - mc
    restart: unless-stopped

  proxy:
    image: itzg/bungeecord
    environment:
      TYPE: VELOCITY
      MINECRAFT_VERSION: 1.20.4
      MEMORY: 4G
      DEBUG: "false"
      ENABLE_RCON: "true"
      PLUGINS: |
        https://hangarcdn.papermc.io/plugins/ReModded/ReWhitelist/versions/1.0.0/VELOCITY/ReWhitelist-1.0.0.jar
        https://download.luckperms.net/1541/velocity/LuckPerms-Velocity-5.4.128.jar
        https://github.com/SkinsRestorer/SkinsRestorer/releases/download/15.0.13/SkinsRestorer.jar
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/4.10.2/PAPER/ViaVersion-4.10.2.jar
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/4.10.2/PAPER/ViaBackwards-4.10.2.jar
        https://github.com/TrueMB/DiscordNotify/releases/download/3.3.5/DiscordNotify-3.3.5.jar
      MODRINTH_PROJECTS: |
        minimotd:z8DFFJMR
        mckotlin:rEHcRyPV
        vlobby:p5lOYrvy
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    networks:
      - mc
    ports:
      - "25565:25577"
    volumes:
      - proxy:/server
    
networks:
  mc:
    name: mc
    driver: bridge

volumes:
  proxy:
    external: true
  Tectonic:
    external: true
  Vanilla:
    external: true
