---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: Internal Dashboard
theme: dark
color: slate
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80 # <----- add this line

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey