---
- hosts: "*"
  become: yes
  become_method: su
  pre_tasks:

    - name: install Server tools
      apt:
        name:
          - git
          - sudo
          - vim
          - neofetch
        update_cache: yes

  tasks:
    - name: install Docker Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository:
        filename: docker
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
    - name: install docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
            # - docker-scan-plugin
          - docker-compose-plugin
          - docker-compose
        update_cache: yes

    - name: Add user to the docker group
      user:
        name: ansible
        groups:
          - docker
          - sudo

    - name: Reboot
      reboot:
        reboot_timeout: 3600

  post_tasks:
    - name: create new volume
      community.docker.docker_volume:
        name: portainer-data

    - name: deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce"
        ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: unless-stopped

    - name: Deploy Portainer Agent
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent
        ports:
          - "9001:9001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volimes:/var/lib/docker/volumes
        restart_policy: unless-stopped