version: '3.8'
services:
  authelia:
    image: authelia/authelia:latest
    ports:
      - 9091:9091:tcp
    environment:
      TZ: ''
    volumes:
      - /portainer/Files/AppData/Config/Authelia:/etc/authelia/
    networks: proxy

networks:
  proxy:
    driver: bridge
    external: true