version: "3.8"
services:
  vanilla:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      VERSION: 1.20.4
      TZ: "America/New_York"
      MEMORY: 2G
    volumes:
      - /portainer/Files/AppData/Config/Vanilla-data:/data
     # - /etc/localtime:/etc/localtime:ro 
     # - /etc/timezone:/etc/timezone:ro
    networks:
      - mc
    restart: unless-stopped

  oasis:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      VERSION: 1.20.4
      TZ: "America/New_York"
      MEMORY: 4G
      TYPE: FABRIC
      MODRINTH_PROJECTS: |
        tectonic:H8adpDEF
        fabric-api:htRy7kbI
        journeymap:YzYzLujr
        fallingtree:mb15RrXi
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - /portainer/Files/AppData/Config/Oasis-data:/data
     # - /etc/localtime:/etc/localtime:ro
     # - /etc/timezone:/etc/timezone:ro
    networks:
      - mc
    restart: unless-stopped
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
     #volumes:
     # - /etc/localtime:/etc/localtime:ro
     # - /etc/timezone:/etc/timezone:ro
    depends_on:
      - vanilla
      - oasis
    environment:
      TZ: "America/New_York"
      MAPPING: |
        vanilla.example.com=mc-vanilla-1:25565
        oasis.example.com=mc-oasis-1:25565
        tekkit2.example.com=tekkit2-tekkit-server-1:25565
    labels:
      - 'traefik.enable=true'
      - "traefik.tcp.routers.minecraft-router.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.minecraft-router.entrypoints=minecraft"
      - "traefik.tcp.services.minecraft-service.loadbalancer.server.port=25565"
    networks:
      - mc
      - tekkit2_default
    restart: unless-stopped
    
networks:
  mc:
    name: mc
  tekkit2_default:
    external: true