version: "2"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    volumes:
      - /opt/container/guacamole/config:/config
    ports:
      - 8888:8080
    restart: unless-stopped 