---
- hosts: "*"
  become: yes
  become_method: su
  tasks:
    - name: install server tools
      become: yes
      apt:
        name:
          - sudo
          - vim
          - git
          - neofetch
          - curl
       state: present