---
- name: Portainer Quick Deployment (Debian)
  hosts: "*"
  pre_tasks:
  become: yes
  become_method: su
    - name: Install Server tools
      apt:
        name:
          - git
          - sudo
          - vim
          - neofetch
        update_cache: yes
  tasks:
  become: yes
  become_method: su
    - name: Install Docker Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
    - name: add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
    - name: add docker repository
      apt_repository:
        filename: docker
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
        state: present
    - name: install docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-scan-plugin
          - docker-compose-plugin
          - docker-compose
        update_cache: yes
        tasks:
    - name: Add user to the docker group
      user:
        name: ansible
        groups: docker
    
  post_tasks:
  become: no
  user: ansible
    - name: create new volume
      community.docker.docker_volume:
        name: portainer-data
    - name: deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce"
        ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
       restart_policy: unless-stopped
    - name: Deploy Portainer Agent
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent
        ports:
          - "9001:9001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volimes:/var/lib/docker/volumes
        restart_policy: always