---
- name: Portainer Quick Deployment Up (Ubuntu)
  hosts: "*"

  pre_tasks:
    - name: install Server tools
      become: yes
      become_method: su
      apt:
        name:
          - git
          - sudo
          - vim
          - neofetch
        update_cache: yes
  tasks:
    - name: install Docker Dependencies
      become: yes
      become_method: su
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
    - name: add docker gpg key
      become: yes
      become_method: su
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository
      become: yes
      become_method: su
      apt_repository:
        filename: docker
        repo: deb [arch=amd64] https://download.docker.com//linux/ubuntu jammy stable
        state: present
    - name: install docker engine
      become: yes
      become_method: su
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-scan-plugin
          - docker-compose-plugin
          - docker-compose
        update_cache: yes
    - name: Add user to the docker group
      become: yes
      become_method: su
      user:
        name: ansible
        groups: docker
  post_tasks:
    - name: create new volume
      become: yes
      become_method: su
      community.docker.docker_volume:
        name: portainer-data
    - name: deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce"
        ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
    - name: Deploy Portainer Agent
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent
        ports:
          - "9001:9001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volimes:/var/lib/docker/volumes
        restart_policy: unless-stopped