---
- hosts: "portainer_servers"
  become: yes
  become_method: su
  tasks:
    - name: update
      become: true
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'