#About: This will copy current ssh banner from host and copy to nodes
---
- hosts: "*"
  become: yes
  become_method: su
  tasks:
    - name: Add Banner
      copy:
        src: /etc/motd
        dest: /etc/motd
        follow: yes