apiVersion: v1
kind: Pod
metadata:
  name: nginx-example
  labels:
    apps: nginx
spec:
  containers:
    - name: nginx
      image: linuxserver/nginx
      ports:
        - containerPort: 80
          name: "nginx-http"