apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: L3s' Internal Dash

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Home:
        header: true
        style: row
        columns: 4
      Self-Hosted:
        header: true
        style: row
        columns: 6
      Monitoring:
        header: true
        style: row
        columns: 1
      Media:
        header: true
        style: row
        columns: 2
      Internal Net:
        header: true
        style: row
        columns: 5
      Access Points:
        header: true
        style: row
        columns: 3
      Servers:
        header: true
        style: row
        columns: 5
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Home:
        - Home Assistant:
            icon: home-assistant.svg
            href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
            description: home
            widget:
                type: homeassistant
                url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
                key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"
        - Mirror:
            icon: wled.png
            href: "{{HOMEPAGE_VAR_MIRROR_url}}"
            description: mirror wled
        - Mon-Wled:
            icon: wled.png
            href: "{{HOMEPAGE_VAR_MON_WELD_url}}"
            description: Monitor Wled's
        - LR-Ambi
            icon: weld.png
            href: "{{HOMEPAGE_VAR_LR_AMBI_url}}"
            description: Living Room Ambilighting
    - Self-Hosted:
        - Trilium:
            icon: trilium.png
            href: "{{HOMEPAGE_VAR_TRILIUM_url}}"
            description: Trilium Notes
        - Guac:
            icon: guacamole.png
            href: "{{HOMEPAGE_VAR_GUAC_url}}" 
            description: Guac
        - Mesh-Central:
            icon: meshcentral.png
            href: "{{HOMEPAGE_VAR_MESH_CENTRAL_url}}"
            description: Mesh-Central
        - Ntfy:
            icon: ntfy.png
            href: "{{HOMEPAGE_VAR_NTFY_url}}"
            description: NTFY
        - SD Webui:
            icon: stablediffusion.png
            href: "{{HOMEPAGE_VAR_SD_WEBUI_url}}"
            description: Stable Diffusion Webui
        - Vault:
            icon: bitwarden.png
            href: "{{HOMEPAGE_VAR_VAULT_url}}"
            description: Vault Warden
    - Monitoring:
      - Uptime-Kuma:
          icon: uptimekuma.png
          href: "{{HOMEPAGE_VAR_UPTIME_KUMA_url}}"
          description: Uptime Kuma
    - Media:
      - Jelly-Fin:
          icon: jellyfin.png
          href: "{{HOMEPAGE_VAR_JELLY_FIN_url}}"
          description: Jelly Fin Media Server
          widget:
            type: jellyfin
            url: "{{HOMEPAGE_VAR_JELLY_FIN_url}}"
            key: "{{HOMEPAGE_VAR_JELLY_FIN_API_KEY}}"
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
      - TransMission:
          icon: transmission.png
          href: "{{HOMEPAGE_VAR_TRANSMISSION_url}}"
          description: TransMission Webapp
    Internal Network:
      - PfSense:
          icon: pfsense.png
          href: "{{HOMEPAGE_VAR_PFSENSE_url}}"
          description: Pf-Sense Firewall
      - Pihole-1:
          icon: pihole.png
          href: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
          description: Pihole 1
          widget:
            type: pihole
            url: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
            key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_1}}"
      - Pihole-2:
          icon: pihole.png
          href: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
          description: Pihole 2
          widget:
            type: pihole
            url: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
            key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_2}}"
      - Arak24P:
          icon: araknis.png
          href: "{{HOMEPAGE_VAR_ARAK24P_url}}"
          description: Araknis 24P Managed Switch
      - NG8P:
          icon: netgear.png
          href: "{{HOMEPAGE_VAR_NG8P_url}}"
          description: Netgear 8P Managed Switch
    Access Points:
      - CH-AP:
          icon: netgear.png
          href: "{{HOMEPAGE_VAR_CH_AP_url}}"
          description: CH A.P (R8000P)
      - Iot-AP:
          icon: netgear.png
          href: "{{HOMEPAGE_VAR_IOT_AP_url}}"
          description: Iot A.P (R7000P)
      - GP-AP:
          icon: asus.png
          href: "{{HOMEPAGE_VAR_GP_AP_url}}"
          description: GP A.P (RT-86U)
    Servers:
      - Teller:
          icon: proxmox.png
          href: "{{HOMEPAGE_VAR_PROXMOX_url}}"
          description: Proxmox VE
          widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
                node: teller
      - Traefik:
          icon: traefik.png
          href: "{{HOMEPAGE_VAR_TRAEFIK_url}}"
          description: Traefik Reverse Proxy
          widget:
            type: traefik
            url: "{{HOMEPAGE_VAR_TRAEFIK_url}}"
      - Truenas:
          icon: truenas.png
          href: "{{HOMEPAGE_VAR_TRUENAS_url}}"
          description: Truenas Core
          widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_TRUENAS_url}}"
      - Portainer:
          icon: portainer.png
          href: "{{HOMEPAGE_VAR_PORTAINER_url}}"
          description: Portainer-ce
          widget:
            type: portainer
            url: "{{HOMEPAGE_VAR_PORTAINER_url}}"
            env: 1
            key: "{{HOMEPAGE_VAR_PORTAINER_API_key}}"
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  docker.yaml: ""