apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      nodePort: 30080
      targetPort: http
  selector:
    app: homepage