---
- hosts: "*"
  become: yes
  become_method: su
  tasks:
    - name: install template packages
      apt:
        pkg:
          - sudo
          - vim
          - qemu-guest-agent
          - cloud-init
        state: present
    - name: start guest qemu-guest-agent
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes

    - name: get files
      shell: "find * -name 'ssh_host*'"
      register: files_to_delete
      args:
        chdir: "/etc/ssh"

    - name:
      file:
        path: "/etc/ssh/{{item}}"
        state: absent
      with_items: "{{files_to_delete.stdout_lines}}"

    - name: clear machine-id
      copy:
        path: /etc/machine-id
        content: ''
        force: yes

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /etc/machine-id
        dest: /var/lib/dbus/machine-id
        state: link

    - name: Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        clean: yes
        autoremove: yes
        purge: true

    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
