version: "3.0"
services:
  littlelink-server:
    image: timothystewart6/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=${META_TITLE}
      - META_DESCRIPTION=${META_DESCRIPTION}
      - META_AUTHOR=${META_AUTHOR}
      - META_KEYWORDS=${META_KEYWORDS}
      - LANG={LANG}
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=${OG_SITE_NAME}
      - OG_TITLE=${OG_TITLE}
      - OG_DESCRIPTION=${OG_DESCRIPTION}
      - OG_URL=${OG_URL}
      - OG_IMAGE=${OG_IMAGE}
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=${THEME}
      - FAVICON_URL=${FAVICON_URL}
      - AVATAR_URL=${AVATAR_URL}
      - AVATAR_2X_URL=${AVATAR_2X_URL}
      - AVATAR_ALT=${AVATAR_ALT}
      - NAME=${NAME}
      - BIO=${BIO}
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=${BUTTON_ORDER}
      # you can render an unlimited amount of custom buttons by adding 
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - CUSTOM_BUTTON_COLOR=#000000,#000000
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff
      - CUSTOM_BUTTON_ICON=fas file-alt,fas fa-cog
      - GITHUB=${GITHUB}
      - TWITTER=${TWITTER}
      - BLUESKY=${BLUESKY}
      - INSTAGRAM=${INSTAGRAM}
      - LINKED_IN=${LINKED_IN}
      - DISCORD=${DISCORD}
      - FOOTER=${FOOTER}
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true