version: "3.0"
services:
  littlelink-server:
    image: timothystewart6/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=L3 Lee
      - META_DESCRIPTION=Systems Administrator | Homelab Nut | 3D Printing Enthusiast | SIM Racer | 🇺🇸 | Tech Obsessed.
      - META_AUTHOR=Leland Rennard
      - META_KEYWORDS=HomeLab, HTML, CSS, Engineering, Systems Administrator, L3, Lee, L3Lee, L3 Lee, lll, lll3,
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=Leland Rennard
      - OG_TITLE=L3 Lee
      - OG_DESCRIPTION=la links de la L3
      - OG_URL=https://lelandrennard.com
      - OG_IMAGE=
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=Dark
      - FAVICON_URL=
      - AVATAR_URL=
      - AVATAR_2X_URL=
      - AVATAR_ALT=Yer
      - NAME=L3 Lee
      - BIO= Systems Administrator | Homelab Nut | 3D Printing Enthusiast | SIM Racer | 🇺🇸 | Tech Obsessed.
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=GITHUB,LINKED_IN,TWITTER,INSTAGRAM,DISCORD,BLUESKY,DOCUMENTATION
      # you can render an unlimited amount of custom buttons by adding 
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - CUSTOM_BUTTON_COLOR=#000000,#000000
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff
      - CUSTOM_BUTTON_ICON=fas file-alt,fas fa-cog
      - GITHUB=https://lelandrennard.com/github
      - TWITTER=https://lelandrenanrd.com/twitter
      - BLUESKY=https://lelandrenanard.com/bluesky
      - INSTAGRAM=https://lelandrennard.com/instagram
      - LINKED_IN=https://lelandrennard.com/linkedin
      - DISCORD=https://lelandrennard/discord
      - FOOTER=Leland Rennard © 2024
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true