global:
  checkNewVersion: true
  sendAnonymousUsage: false
   
entryPoints:
  http:
    address: ":80"
    http:
     redirections:
      entryPoint:
        to: https
  https:
    http:
      middlewares:
        - default-headers@file
    address: ":443"
    forwardedHeaders:
     insecure: true
serversTransport:
  insecureSkipVerify: true 
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /etc/traefik/config.yml

# Enable traefik ui
api:
  dashboard: true
  debug: true

# Log level INFO|DEBUG|ERROR
log:
  level: INFO

# Use letsencrypt to generate ssl serficiates
certificatesResolvers:
 cloudflare:
    acme:
      email: <EMAIL>
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"