version: "3.1"
services:
  groupoffice:
    image: intermesh/groupoffice:testing
    restart: always
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - "godata:/var/lib/groupoffice:cached"
      - "goetc:/etc/groupoffice:cached"
#      - "gostudio:/usr/local/share/groupoffice/go/modules/studio:cached"
      - ./src/studio:/usr/local/share/groupoffice/go/modules/studio


    #      Example for ssl
#      - "./config/ssl/groupoffice:/etc/ssl/groupoffice"  
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: groupoffice
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - "dbdata:/var/lib/mysql:cached"
volumes:
  godata:
  goetc:
  #gostudio:
  dbdata: